ai-client:
  ollama:
    base-url: http://localhost:11434
    chat:
      options:
        model: gemma3:4b
        temperature: 0.7
    embedding:
      options:
        model: mxbai-embed-large
server:
  port: 8086
  servlet:
    context-path: /AiServiceClient
spring:
  profiles:
    active: ollama
  datasource:
    url: jdbc:postgresql://localhost:5434/dms_db?currentSchema=vectorcontent
    username: postgres
    password: toor
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      default_schema: vectorcontent
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/DocumentContent-DOC_MANAGEMENT_DB/changelog-master.xml
    default-schema: vectorcontent
spring-doc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    filter: true
    operations-sorter: alpha
  api-docs.path: /v3/rest-api-docs

logging:
  level:
    org:
      springframework:
        web: DEBUG
        data: DEBUG
