server:
  port: 8086
  servlet:
    context-path: /AiServiceClient
spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        model: gpt-3.5-turbo-1106
  datasource:
    url: jdbc:postgresql://localhost:5434/doc_management_db
    username: postgres
    password: toor
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      default_schema: vectorcontent
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/DocumentContent-DOC_MANAGEMENT_DB/changeLog-master.xml
    default-schema: vectorcontent
spring-doc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    filter: true
    operations-sorter: alpha
  api-docs.path: /v3/rest-api-docs

logging:
  level:
    org:
      springframework:
        web: DEBUG
        data: DEBUG